### ISSUE TITLE
Small mistake

### ISSUE THREAD

**Issue by YairGatt** [UCanCompBio/deltaBS#3]
Wiki accidentlly says "When running deltaBS, the option -hd specifies the directory that HMMER3 has been installed in and -hp specifies the directory that the Pfam HMMs have been dowloaded to."
Instead of "When running deltaBS, the option -hp specifies the directory that HMMER3 has been installed in and -hd specifies the directory that the Pfam HMMs have been dowloaded to."

**Comment by lbarquist** [comment]
Thanks for pointing this out, I've fixed it now.
