### ISSUE TITLE
Is there a misspelled a variable "counts" at src/deltaBS.pl lines 507 and 563?

### ISSUE THREAD

**Issue by uyghbo** [UCanCompBio/deltaBS#5]
Global symbol "$counts" requires explicit package name (did you forget to declare "my $counts"?) at src/deltaBS.pl line 507.
Global symbol "$counts" requires explicit package name (did you forget to declare "my $counts"?) at src/deltaBS.pl line 563.

I manually  change it to “count” and it works well.

**Comment by nwheeler443** [comment]
Ahh yes, that was a typo, thank you for catching it!
